### ISSUE TITLE
symlinks don't show

### ISSUE THREAD

**Issue by normanr** [sole/aafm#12]
symlinks have a 'l' as the permissions bit, and produce the "wasn't matched, please report to developer!" error message.

It would be nice if symlinks were shown in the window.

**Comment by sole** [comment]
Thank you for spotting this!

I guess you mean symlinks device side. I'll see what can I do.

**Comment by sole** [comment]
(Possibly related with issue #1 ?)

**Comment by normanr** [comment]
issue #1 seemed to be about broken symlinks, which I don't think is the problem here.

I think this would be easy to fix quickly by allowing 'l' in the permissions bit, and stripping the " -> .*" suffix from the filename.
