### ISSUE TITLE
.desktop file

### ISSUE THREAD

**Issue by sole** [sole/aafm#14]
It'd be nice to have one. Not sure how it would work if this is packaged into a distribution.

**Comment by Huulivoide** [comment]
I'm working on this on my branch. Plan is to add .desktop file, wrapper script [done]
to find the name of python2 executable and setup.py script for proper install.

**Comment by sole** [comment]
Oh, that's great, many thanks! :-)

I looked at your branch but there's nothing commited yet. I guess I'll have to wait then...

If you have a .desktop file, will aafm show up in Gnome 3's menu? (I mean the one that shows up when you click on Activities)

**Comment by sole** [comment]
Implemented thanks to Huulivoide! Yay! \o/
