### ISSUE TITLE
gvfs-gphoto2 conflict

### ISSUE THREAD

**Issue by texkelly** [sole/aafm#15]
On my RHEL6.2 machine if I unplug and replug the USB aafm no longer works and I get gvfs related USBDEVFS error messages similar to the below:
usb 1-1.2: usbfs: USBDEVFS_CONTROL failed cmd adb rqt 128 rq 6 len 256 ret -71

It looks to be some sort of conflict with gvfs-gphoto2 as I disabled the volume mounter by changing the pointer in /usr/share/dbus-1/services/org.gtk.Private.GPhoto2VolumeMonitor.service to a dummy entry and rebooted and it's now all working again.

Old /usr/share/dbus-1/services/org.gtk.Private.GPhoto2VolumeMonitor.service:
[D-BUS Service]
Name=org.gtk.Private.GPhoto2VolumeMonitor
Exec=/usr/libexec/gvfs-gphoto2-volume-monitor

New /usr/share/dbus-1/services/org.gtk.Private.GPhoto2VolumeMonitor.service:
[D-BUS Service]
Name=org.gtk.Private.GPhoto2VolumeMonitor
Exec=/usr/libexec/gvfs-gphoto2-volume-monitorx

Not sure if there's anything you can do but at least other users can learn from my tribulations.

**Comment by sole** [comment]
Thanks for taking the time to write here your tribulations :D

I admit I'm at a loss as to what to do here. I haven't had that issue and I've used aafm with several Gnome incarnations... Which version of Gnome are you using?
