### ISSUE TITLE
multiple device support

### ISSUE THREAD

**Issue by normanr** [sole/aafm#16]
"adb devices" gives a list of connected devices

serial number can be set in env['ANDROID_SERIAL]' or passed as "-s <serial number>" on adb command line.

**Comment by normanr** [comment]
fwiw: "shell getprop ro.product.model" will return a human readable model that could be used for device selection.

**Comment by normanr** [comment]
btw, a work around is to set ANDROID_SERIAL before running aafm :-)  This works perfectly!

**Comment by sole** [comment]
Brilliant, Norman! I'm actually working with more than one device recently. I think having a drop down sort of selector would be very useful in this scenario.

And the product.model tip is great! I'll implement that as soon as I can

**Comment by sole** [comment]
done in #59
