### ISSUE TITLE
Insufficient permissions for device

### ISSUE THREAD

**Issue by alexalex89** [sole/aafm#2]
Hey,

at first let me say, keep up the good work! The tool is a real good idea!

My problem is, ADB gives me an error saying 
"
EXECUTE= adb shell ls -la "/mnt/sdcard/"
error: insufficient permissions for device
"
after starting aafm-gui.py.

I've got a Galaxy Tab 10.1 with Android 3.1, Kernel 2.6.36.3 and Build HMJ37 P7500XWKG9. (If necessary) It's not rooted and Development mode is enabled.
lsusb says:
"
Bus 002 Device 008: ID 04e8:685e Samsung Electronics Co., Ltd
"

It'd be nice if you continue developing this nice tool and help poor non-windows-users like me ;-)

Best wishes,
Alex

**EDIT**
Additional information:
The tool also says:
"
- daemon not running. starting it now on port 5037 \* wasn't matched, please report to the developer!
- daemon started successfully \* wasn't matched, please report to the developer!
  "

I am using Ubuntu 11.04.

**Comment by sole** [comment]
If you get the insufficient permissions for device error, it means your device is not properly configured in Ubuntu.

You need to add a file to the /etc/udev directory which will allow all users to access the USB device (hence they'll have permissions!)

For example mine is in /etc/udev/rules.d/51-android.rules and for the Samsung device I have this:

```
 # Samsung
 SUBSYSTEM=="usb", SYSFS{idVendor}=="04e8", MODE="0666"
```

I think for Ubuntu 11.4 something in the syntax of the rules has changed, but you should be enough to go and look for more info. I am using 10.10 still :D

**Comment by alexalex89** [comment]
Thanks for the hint. It works now, but only logged in as root with "sudo -i". Whatever - it's working. Thank you!

**Comment by sole** [comment]
Try using 

```
MODE="0777"
```

that should allow you to connect and use the device without the sudo part (hopefully!)

**Comment by alexalex89** [comment]
Thank you, it worked!
Now I tried to copy an mp3-file with 2.6MB and the status bar freezed immediately. I waited for 5 minutes and it wasn't moving :-( I guess it's not only slow, but not working. There's no error message in the terminal. (There's also no command printed)

**Comment by sole** [comment]
Might I suggest you try first with a smaller file and see if it works?

Longer files sometimes seemingly get the window frozen--though it's not actually the case. That's on the README file anyway O:-)

**Comment by alexalex89** [comment]
Hey Sole,

okay. I tried it with a textfile of 5 Bytes and it still didn't work. Oh right, it just seems that the window is frozen (because of the statusbar not moving). The file is not moving and the folder still empty. (After refreshing) There's no error message in the terminal.

Thank you and best wishes,
Alex

**Comment by sole** [comment]
That's strange...

Can you check that the computer can effectively connect with the device? Just open ddms and see if you can browse files with it (as it uses the same system that aafm uses!)

ddms is in the SDK, in SDK_PATH/tools/ddms

So once it's open --and if hopefully you don't get any error message-- you should be able to see the device on the left pane. Click on it to highlight it and then choose Device -> File Explorer

If that works and you can browse around then there's something wrong in my code :D

**Comment by alexalex89** [comment]
I tried out clicking right on the file I want to copy and choose "Copy to device". That's working! It's only drag-and-drop from host to device which is not working. (From device to host is working perfectly using drag-and-drop.)
So my problem is solved.
Thank you very much for your help and the tool!

**Comment by sole** [comment]
Ah, that's interesting. Will have to investigate why that doesn't work... I'll let you know if I need some more info!

Thanks for the testing :)
