### ISSUE TITLE
ls -la fails on my device

### ISSUE THREAD

**Issue by thjc** [sole/aafm#3]
on my device (android 2.3.4 xperia ray) adb shell ls -la fails to execute as it interprets the 'a' as a file to list. It works great if "ls -la ..." is replaced with "ls -l -a ...".

**Comment by sole** [comment]
hello!

I don't have the tablet here right now--will test it as soon as I can and integrate the change if it works, okay? :-)

Thanks for pointing this out!

**Comment by sole** [comment]
Done!

**Comment by thjc** [comment]
Great, thanks for making the tool, very handy
