### ISSUE TITLE
Escape paths

### ISSUE THREAD

**Issue by sole** [sole/aafm#33]
Using paths with parenthesis generates `Syntax error: "(" unexpected in the device` types of errors.

Must ensure paths are properly escaped before using them.

But what are the "forbidden" characters?

**Comment by normanr** [comment]
what about using pipes.quote (it's badly documented, and has moved to shlex.quote in py3k) instead of a custom device_escape_path function?

**Comment by sole** [comment]
`device_escape_path` is meant to encapsulate whatever function we decide to use for escaping :D

I didn't know about quote... and obviously the function I was using was poor! (hence the 'what are the forbidden characters' self-question). But it solved the problem I was having with parenthesis in paths.

I'll have a look, thanks for the pointer. You're always spot on! :-)

**Comment by sole** [comment]
Looks like it's working now. _fingers crossed_
