### ISSUE TITLE
Windows - Incorrect path separator 

### ISSUE THREAD

**Issue by psinnott** [sole/aafm#4]
When run under windows the wrong file path separator is used for the device. This causes problems when displaying the root directory and copying files (probably other places too).

As an easy fix I added 

command = str.replace( command  , "\" , "/" );

as the first line of the execute function in AAfm.py

**Comment by sole** [comment]
Hello!

Hopefully this is fixed now. However as I told you I don't have a Windows machine to test this... so if you feel like having a look it would be awesome! :-)

I'll close the issue, feel free to reopen if you think it doesn't work.
