### ISSUE TITLE
Nowhere to set the initial path

### ISSUE THREAD

**Issue by Firef0x** [sole/aafm#46]
Hi! Thx to ur great work on aafm. It impresses me a lot & remind me of the wonderful moment using Total Commander on Windows. ^_^  But could u pls make a configuration file such as .aafmrc for usrs setting the initial path rather than os.getcwd() and '/mnt/sdcard'? In my system(Arch Linux), it leads me to /home/usr/Documents which is not exist. I'm border to click .. every time. Sorry for my broken English, I'm just a newbie.  -.-!

Hope ur program be yet another Total Commander bridging PC and Android!

Thanks and Regards,

**Comment by Firef0x** [comment]
Maybe u can solve it by remembering last directory. Like what you issue in 
https://github.com/sole/aafm/issues/21

**Comment by sole** [comment]
Yes, that's the idea in #21

I don't understand how can it bring you to `/home/usr/Documents`
That is not hardcoded anywhere in the source, but that might be what your system is returning to getcwd(). See, here is where the initial directories are set:
https://github.com/sole/aafm/blob/master/src/aafm-gui.py#L40

As you can see it's just

``` python
self.aafm = Aafm('adb', os.getcwd(), '/mnt/sdcard/')
```

Feel free to investigate if you feel like that, but it works fine in the systems I've tested so far :-)
Might be something odd with your configuration/setup...

**Comment by Firef0x** [comment]
I don't understand too.But it REALLY bothers me. And I'm not vacant to debug verbosely. However, I'm not a pythoner, incapable for committing...

P.S. diversity among different Linux & Android releases REALLY bother coders, hope u can be patient... I'm using Arch Linux + KDE SC 4.9 and MIUI V4 2.9.28 on LG Nitro HD, hope this helps.

**Comment by sole** [comment]
It's ok. Please just wait until I implement #21 then.

I'm going to close this issue as it will be resolved when #21 is.

Thanks for your collaboration :-)

**Comment by Firef0x** [comment]
Excellent! Feeling efficient in GitHub!! Nobody ever responses when I put an issue in Google Code T-T

**Comment by sole** [comment]
Google Code isn't nowhere as active as Github I think :-)

One question though... where did you heard about aafm? It seems there are a lot of new users recently but I don't know where are you coming from! And I'm intrigued! :-D

**Comment by Firef0x** [comment]
Project in Google Code as small as this one, the maintainer is as lazy as a koala.~_~
When I search keyword 'android' in the holy great almighty Arch User Repository, aafm comes up first(Since it begins with aa...Is it on purpose?), and I just have a try...

P.S. Although Arch Linux uses Python 3.2 as default, I only have Python 2.7.3 and have linked /usr/bin/python2 to /usr/bin/python, with PyGTK support. In some comments you refered to the python release problem on Arch Linux, but I think that it isn't the reason why os.getcwd() leads to /home/usr/Documents.The aafm apps are in /usr/bin and my default documents path is /home/usr/文档.(Chinese, means Documents, but I think python can get it correctly)

Hope this helps.

Thanks and Regards.

**Comment by sole** [comment]
But what is your user name? Is your username "usr"?

Regarding the name of aafm, it wasn't chosen so that it would appear first on the list! But because it means Android ADB File Manager = AAFM :-)
