### ISSUE TITLE
Windows - Unixisims (pwd/grp)

### ISSUE THREAD

**Issue by psinnott** [sole/aafm#5]
aafm-gui imports and uses pwd and grp. An appropriate Windows replacement seems to be 

```
def get_owner(self, filename):
    #st = os.stat(filename)
    #uid = st.st_uid
    #user = pwd.getpwuid(uid)[0]
    #return user

    import win32api
    import win32con
    import win32security
    sd = win32security.GetFileSecurity( filename , win32security.OWNER_SECURITY_INFORMATION)
    owner_sid = sd.GetSecurityDescriptorOwner()
    name, domain, type = win32security.LookupAccountSid (None, owner_sid)
    return name

def get_group(self, filename):
    #st = os.stat(filename)
    #gid = st.st_gid
    #return grp.getgrgid(gid)[0]
    return ""
```

**Comment by sole** [comment]
Thanks for the two issues/patches. I'll try to merge them into the code as soon as I can. However I don't have a Windows machine to test... so I'll have to require your help! :-)

**Comment by psinnott** [comment]
Always happy to help.

There was another problem but I am not sure about it so I didn't open an issue. ls on my phone seems to produce a slightly different output than the script expects. Maybe it is something to do with the rom.

**Comment by sole** [comment]
Out of curiosity: which rom are you using?

Does it break things or does the app keep working even if the output is slightly different? Maybe we can accommodate some sort of alternative parsing for those cases. Feel free to open another issue so we can keep an eye on these things :-)

And many thanks again--will do some work on this soon! :D

**Comment by sole** [comment]
OK hopefully this should work, if you fancy testing it, Windows users will be happy :-)

closing and thanks for the code :-)
