### ISSUE TITLE
Do not show hidden files and folders

### ISSUE THREAD

**Issue by mardukbp** [sole/aafm#53]
A typical home directory in a UNIX filesystem contains several "invisible" files and directories. Therefore the left pane in `aafm` becomes a pain when showing the home dir. I might be wrong, but I believe most people will not want to copy their `.bashrc` over to their tablet. Perhaps there should be a button to hide them or show them. 

I suggest the default behavior of `dir_scan_host` should be

```
root, dirs, files = next(os.walk(directory))
files = [f for f in files if not f[0] == '.']
dirs = [d for d in dirs if not d[0] == '.']
```

Thanks for this awesome program!

**Comment by sole** [comment]
Thanks, glad it's useful for you.

If you want to implement that feature with a checkbox or option of sorts I'd be glad to merge it :-)
Filezilla has something similar, so I can see it being helpful.
