### ISSUE TITLE
Branch into nfs mountpoint not working

### ISSUE THREAD

**Issue by mclane** [sole/aafm#8]
When I try to branch into the filesystem behind a nfs moutpoint I get the following error:

Traceback (most recent call last):
  File "./aafm-gui.py", line 152, in host_navigate_callback
    self.refresh_host_files()
  File "./aafm-gui.py", line 170, in refresh_host_files
    self.host_treeViewFile.load_data(self.dir_scan_host(self.host_cwd))
  File "./aafm-gui.py", line 222, in dir_scan_host
    'owner': self.get_owner(path),
  File "./aafm-gui.py", line 271, in get_owner
    user = pwd.getpwuid(uid)[0]
KeyError: 'getpwuid(): uid not found: 1026'

Jumping back via .. does not work either.

**Comment by sole** [comment]
Sorry, with "nfs", do you mean "network file system"?

Which host system are you using? Linux? distro...?

Thanks for the report!

**Comment by mclane** [comment]
Probably I was too short in the description - sorry for that.

I have a network-attached storage device (Synology DS210j) where I store my media (music video etc.) centrally. My host PC is running Linux (Ubuntu 11.10). The NAS filesystem is connected to the host PC file system using the Unix Network File System (NFS) via a mount point  (/media/nfs) in the Linux file tree. When I want to browse on the host PC into the NFS in order to upload some files into the Honeycomb tablet, the error occurs. I also cannot browse back any more. I have no problem accessing the files in the NAS via the normal Ubuntu Nautilus file system browser.

Hope that clarifies the situation

**Comment by sole** [comment]
It's alright -we can always ask for clarifications! :-)

I'll try to figure out why does it fail, given the trace you provided earlier. I don't have any NAS but I'll try to make the software at least more robust so that it doesn't totally break when an error occurs! :-)
